### ISSUE TITLE
code hang up on teensy 4.0

### ISSUE THREAD

**Issue by AzwarPrihastomo** [DFRobot/DFRobot_TMF8x01#1]
Hi

i just test this code on teensy 4.0 and it freeze
after debug and fixed on this function

void DFRobot_TMF8x01::conversion(String str, uint8_t *buf, uint8_t &len, uint8_t checksumbit){
  uint8_t count = 0,sum = 0;
  int i;
  bool checksumFlag = false;
  String subStr;
  str.toUpperCase();
  str.trim();
  str += ',';
  while((i = str.indexOf(',')) > -1){
      if( i != 0){
          subStr = str.substring(0, i);
          subStr.trim();
          if((subStr.length()==4) && (subStr[0]=='0') && (subStr[1]=='X')){
              buf[count++] = getCharHex(subStr[2])*16 + getCharHex(subStr[3]);
              
              if((count-1) >= checksumbit) sum += buf[count - 1];
          }
      }
      if((str.length() - i) < 4)
        break;
      str = str.substring(i+1);
      str.trim();
  }
  
  if(count > checksumbit) buf[count++] = sum ^ 0xff;
  len = count;
}

i only guard for next iteration
      if((str.length() - i) < 4)
        break;

thanks

**Comment by Arya11111** [comment]
Thank you for your feedback. I have addressed the issue. 
add The follow condition to quit  while 
`if (str.length() <= (i + 1)) break;`
